period: 1000000
masters:
  - id: 0
    type: ethercat
    number_of_slaves: 2
    ethercat_master_index: 0
    slaves:
      - controller_index: 0
        driver_id: 0
        alias: 2
        position: 0
        vendor_id: 0x5a65726f
        product_id: 0x00029252
        profile_mode: 0 # 0: Position Mode, 1: Velocity Mode, 2: Effort Mode

      - controller_index: 1
        driver_id: 0
        alias: 4
        position: 0
        vendor_id: 0x5a65726f
        product_id: 0x00029252
        profile_mode: 0 # 0: Position Mode, 1: Velocity Mode, 2: Effort Mode

drivers:
  - id: 0
    pulse_per_revolution: 524288
    rated_effort: 52.0
    unit_effort: 0.1
    lower: -100.0
    upper: 100.0
    speed: 3000
    acceleration: 143.2394487827
    deceleration: 143.2394487827
    profile_velocity: 143.2394487827
    profile_acceleration: 143.2394487827
    profile_deceleration: 143.2394487827
    profile_position_value: 1
    profile_velocity_value: 3
    profile_effort_value: 4
    type: zeroerr
    param_file: ../param
