#!/usr/bin/env python3

from rqt_gui.main import Main
from motion_control_rqt.motion_control_controller import MotionControlController

import sys


plugin = 'motion_control_rqt.motion_control_controller.MotionControlController'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
