<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>xtouch_midi</name>
  <version>0.1.0</version>
  <description>
    ROS 2 bridge for Behringer X-Touch MIDI faders. Publishes full MIDI state.
  </description>
  <maintainer email="seonilchoi98@gmail.com">mini0</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>midi_msgs</depend>

  <build_depend>pkg-config</build_depend>
  <depend>librtmidi-dev</depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
